### ISSUE TITLE
치킨의 카테고리에 대해 조사해주세요!!

### ISSUE THREAD

**Issue by soongu** [soongu/chicken-history#2]
- category-of-chicken.txt 파일을 생성해주세요
- 치킨 카테고리와 종류를 조사해 작성하세요

**Comment by soongu** [comment]
혹시 언제까지 가능하실까요???

**Comment by soongu** [comment]
대답좀 ㅎㅎ

**Comment by SoonguHong** [comment]
![](https://imagecdn.skstoa.com/goods/344/33328344_g.jpg)
